apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ .Values.name | required "A resource name is required." }}
  annotations:
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.argoSyncWave }}
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWave | quote }}
    {{- end }}
  labels:
    {{- include "iam-service-account.labels" . | nindent 4 }}
spec:
  displayName: {{ .Values.name | replace "-" " " | title }}
  description: {{ .Values.spec.description | quote}}
  disabled: {{ .Values.spec.disabled | default false }}
